services:
  nfsus-testing:
    image: ghcr.io/mmbesar/nfsuserver-container:testing
    container_name: nfsus-testing
    restart: unless-stopped
    ports:
      - "10900:10900/tcp"
      - "10901:10901/tcp" 
      - "10980:10980/tcp"
      - "10800:10800/udp"
      - "10800:10800/tcp"
      - "80:80/tcp"          # Web UI
    volumes:
      - ./data:/data
      - ./logs:/var/log/nfsu
    environment:
      - TZ=Africa/Cairo
    healthcheck:
      test: ["CMD", "sh", "-c", "pgrep nfsuserver && pgrep nginx && pgrep php-fpm83"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
