name: Build & Push per-arch Docker Image

on:
  push:
    paths:
      - 'Dockerfile'
      - 'Dockerfile.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      # 1. Get your code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Prepare Buildx + QEMU
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Register QEMU for emulation
        uses: docker/setup-qemu-action@v2

      # 3. Login to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Dynamically lowercase your owner/repo
      - name: Compute lowercase image name
        id: lowercase
        run: |
          # $GITHUB_REPOSITORY is like "MyUser/MyRepo"
          IMAGE=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
          echo "image_name=$IMAGE" >> $GITHUB_OUTPUT

      # 5. Build & push per-arch
      - name: Build and push ${{ matrix.arch }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.image_name }}:latest-${{ matrix.arch }}
            ghcr.io/${{ steps.lowercase.outputs.image_name }}:${{ github.sha }}-${{ matrix.arch }}
